#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! head -1 "$1" | grep -qE "^(init|feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo "Aborting commit due to invalid commit message format. Ensure your commit message starts with a valid prefix (feat, fix, chore, docs, test, style, refactor, perf, build, ci, revert) followed by an optional scope in parentheses, a colon, and a space. Example: 'feat(scope): description'" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi